{
  "formatVersion": "1.1",
  "component": {
    "group": "im.amomo.andun7z",
    "module": "libraryx",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uloozhxz5rcjvfe7vgjo2tu6tq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libraryx-1.2.1.aar",
          "url": "libraryx-1.2.1.aar",
          "size": 148635,
          "sha512": "7095d47ac075142c5da081365a9f0dab70e2e7db64d4b7215fe9ff03cad274fbe96eaaa47e4e7024d177159abdfe0f62aba74be95321644c7ee5f8d94e764eba",
          "sha256": "fd2b9ddfad1cc6b73ee0356ef63fddf08d496f33aec6dbdd97c89acecf429709",
          "sha1": "64bc464511df50de6920351101f7725b3f932571",
          "md5": "8f1a1b61a02996eb9a226705e3d536f7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libraryx-1.2.1.aar",
          "url": "libraryx-1.2.1.aar",
          "size": 148635,
          "sha512": "7095d47ac075142c5da081365a9f0dab70e2e7db64d4b7215fe9ff03cad274fbe96eaaa47e4e7024d177159abdfe0f62aba74be95321644c7ee5f8d94e764eba",
          "sha256": "fd2b9ddfad1cc6b73ee0356ef63fddf08d496f33aec6dbdd97c89acecf429709",
          "sha1": "64bc464511df50de6920351101f7725b3f932571",
          "md5": "8f1a1b61a02996eb9a226705e3d536f7"
        }
      ]
    }
  ]
}
