{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.princekin-f",
    "module": "easyfloatx",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "shalntkzknaevnjlhyc6tuibha"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "easyfloatx-1.0.aar",
          "url": "easyfloatx-1.0.aar",
          "size": 136839,
          "sha512": "a683bb98c283ada6f5d2882cc8538594d25693284f3daf59f48755a89e234fb7a9ca06967f02741f60f476a2e902fc70bd5d756fac50e8e0a6772d5f8d13cfe5",
          "sha256": "87abe414a32ad39762a03ea00b4a6a826a139bd96ce8462b19b04cefaa490d05",
          "sha1": "5be70da8e28802af353af315cba4a956a78f7b4f",
          "md5": "ac7aabb101bbc7a5b45a665a93e692fc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "easyfloatx-1.0.aar",
          "url": "easyfloatx-1.0.aar",
          "size": 136839,
          "sha512": "a683bb98c283ada6f5d2882cc8538594d25693284f3daf59f48755a89e234fb7a9ca06967f02741f60f476a2e902fc70bd5d756fac50e8e0a6772d5f8d13cfe5",
          "sha256": "87abe414a32ad39762a03ea00b4a6a826a139bd96ce8462b19b04cefaa490d05",
          "sha1": "5be70da8e28802af353af315cba4a956a78f7b4f",
          "md5": "ac7aabb101bbc7a5b45a665a93e692fc"
        }
      ]
    }
  ]
}
